runtime: python27
api_version: 1
threadsafe: true

# [START inbound services]
inbound_services:
- mail
# [END inbound services]

# [START handlers]
handlers:
# catch all incoming emails
- url: /_ah/mail/.+
  script: EmailHandlerV1.app
  login: admin
  
# a more sophisticated approach
#- url: /_ah/mail/owner@.*your_app_id\.appspotmail\.com
#  script: handle_owner.app
#  login: admin
#- url: /_ah/mail/support@.*your_app_id\.appspotmail\.com
#  script: handle_support.app
#  login: admin
#- url: /_ah/mail/.+
#  script: handle_catchall.app
#  login: admin
# [END handlers]

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap
- url: /jquery
  static_dir: jquery
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /js
  static_dir: js

- url: /v1/content/.*
  script: ContentHandlerV1.app

- url: /v1/api/.*
  script: ApiHandlerV1.app

- url: /.*
  script: MainHandler.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
